apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  labels:
    app: eureka-nodeport
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 31761
      name: client
  selector:
    app: eureka