apiVersion: v1
kind: Pod
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  hostname: eureca-demo
  subdomain: spring
  containers:
  - name: eureca
    image: "pengtaoman/eureka:v0.0.2"
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8761
        name: client
---
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
spec:
  clusterIP: None
  ports:
    - port: 8761
      targetPort: 8761
      name: client
  selector:
    app: eureka